services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    depends_on:
      - db
    profiles: ["test"]

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workerdb
    ports:
      - "5432:5432"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
