name: .NET CI

on:
  push:
    branches: [ "*" ]   
  pull_request:
    branches: [ "main" ]  

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore GestaoPessoas.sln

    - name: Build solution
      run: dotnet build GestaoPessoas.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test GestaoPessoasTests/GestaoPessoasTests.csproj --verbosity normal
